title: understand animals
author: Amanda Matthes
description: tools to understand and help animals
baseurl: ""
url: "https://understandanimals.github.io"
theme: minima
plugins:
header_pages:
 - about.md
 - contact.md