title: understand animals
author: Amanda Matthes
description: tools to understand animals
baseurl: ""
url: "https://understandanimals.github.io"
theme: minima
plugins:
header_pages:
 - projects.md
 - about.md
 - contact.md